### ISSUE TITLE
Issue Number 3

### ISSUE THREAD

**Issue by L-the-forgettable** [glotchalotch/Funkin-duet#3]
I'm back, yet again. Better to have one person reporting back rather than none.

Windows, 64 bit, 1.6.2

Under the "section" tab in the editor, there is a "clear" button. I would assume this button is placed to allow one to remove all notes from a section. This function majorly works as intended, doing its job on the main charting flawlessly. That is till it is used on a duetted char's charting. It functions as intended, Untill you try and save the json file, or play that section in the charting. At which point, the game crashes.

**Comment by glotchalotch** [comment]
turns out clearing a section leaves the song object looking like this: ```"duetSectionNotes" : [
                     [
                    ]
                ]```
i wrote the code so that it checked if the arrays *exist*, but i didn't check to make sure there was actually anything *in them.* what i need to do is just delete those empty arrays entirely, but simple checks for null will do for now.

**Comment by glotchalotch** [comment]
turns out by "for now" i meant for 20 minutes. now it actually fully clears the section from the chart when it's deleted. this will help reduce bloat in the chart json as well
